######################################################################
# Automatically generated by qmake (3.0) Wed Mar 6 15:34:02 2013
######################################################################

TEMPLATE = app
TARGET = QtSensors
INCLUDEPATH += .
QT += qml network quick widgets opengl sensors quickcontrols2
QTPLUGIN += qtsensors_android qtsensors_generic #qtsensors_ios

# Input
SOURCES += main.cpp
RESOURCES += main.qrc
OTHER_FILES += main.qml ball.jpeg
